version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - POSTGRES_CONN=postgresql://postgres:1234@db:5432/tender
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8080

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tender
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/docker-entrypoint-initdb.d
